# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H4z8Q7-ItMz73SVfdMUKJTBUMhUEIQEK
"""

import pandas as pd,numpy as np,matplotlib.pyplot as plt,seaborn as sns

dt=pd.read_csv("food_risk_dataset.csv")

dt.iloc[0].drop(["risk"]).to_numpy()

dt.temperature=dt.temperature.map({"refrigerated temperature":0,"cool temperature(approx. 18 C)":1,"room temperature(more than 25 C)":2})

dt.food_type=dt.food_type.map({"Cooked rice dish":0,"Non-veg curries":1,"Dairy-based curries":2,"Dal/lentils":3,"Gravy-based veg curries":4,"Fresh breads":5,"Dry vegetable dishes":6,"Fried items":7,"Sweets":8})

dt.risk=dt.risk.map({"very high":3,"high":2,"medium":1,"low":0})

dt.drop('Unnamed: 0', axis=1, inplace=True)

dt

from sklearn.preprocessing import StandardScaler

hours_scaled=StandardScaler().fit_transform(dt[["hours_already_spent"]])

hours_scaled

dt['hours_already_spent']=pd.DataFrame(hours_scaled)

from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test=train_test_split(dt.drop("risk",axis=1),dt.risk,train_size=0.8)

from xgboost import XGBClassifier

from sklearn.model_selection import GridSearchCV

X_train

from sklearn.metrics import accuracy_score

def XGB(X_train,Y_train,X_test,Y_test):
  cv=GridSearchCV(estimator=XGBClassifier(),param_grid={'n_estimators':[5,10,30,50,70],'max_depth':[2,5,8,10],'learning_rate':[0.1,0.2,0.5,0.7]},cv=3,n_jobs=-1)
  cv.fit(X_train,Y_train)
  param_xgboost=cv.best_params_
  model=XGBClassifier( learning_rate=param_xgboost['learning_rate'] , max_depth=param_xgboost['max_depth'] , n_estimators=param_xgboost['n_estimators'], random_state=42)
  model.fit(X_train,Y_train)
  prediction_test=model.predict(X_test)
  accuracy=accuracy_score(Y_test,prediction_test)
  return [accuracy,param_xgboost]

params_accuracy=XGB(X_train,Y_train,X_test,Y_test)

params_accuracy

model=XGBClassifier(learning_rate=params_accuracy[1]['learning_rate'],max_depth=params_accuracy[1]['max_depth'],n_estimators=params_accuracy[1]['n_estimators'])
model.fit(X_train,Y_train)
model.save_model("xgb_foodrisk_model.json")

model.predict(pd.DataFrame([[6,1,0.5592153335822942]], columns=['food_type', 'temperature', 'hours_already_spent']))

